name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./Movie-Suggester-SE3-SS-6-Filter-by-Genre
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Navigate to project and install dependencies
        run: |
          cd ./Movie-Suggester-SE3-SS-6-Filter-by-Genre
          npm install
          npm install --save-dev jest
      
      - name: Run tests
        run: |
          cd ./Movie-Suggester-SE3-SS-6-Filter-by-Genre
          npm test
